# NumPy

# NumPy

-   NumPy is short for Numerical Python

-   ndarray, an efficient multidimensional array providing fast
    array-oriented arithmetic operations

-   Math functions for fast operations to avoid writing loops

-   Linear algebra and random number generation

-   Designed for large arrays of data

    ``` {r}
    library(reticulate)
    ```

    ``` python
    #creating a ndarray

    import numpy as np 

    data1 = [6, 7.5, 8, 0, 1]

    arr1 = np.array(data1)

    print(arr1)
    ```

        [6.  7.5 8.  0.  1. ]

In [2]:
#Examples of batch computation 
print(data1 * 20)


print(data1 + data1)

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]
[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

-   In addition to numpy.array, numpy.zeros and numpy.ones can be used
    to create arrays of 0s or 1s with a given shape  

    ``` python
    print(np.zeros(5))

    print(np.zeros((5,7)))

    print(np.ones((5,7)))
    ```

        [0. 0. 0. 0. 0.]
        [[0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0.]]
        [[1. 1. 1. 1. 1. 1. 1.]
         [1. 1. 1. 1. 1. 1. 1.]
         [1. 1. 1. 1. 1. 1. 1.]
         [1. 1. 1. 1. 1. 1. 1.]
         [1. 1. 1. 1. 1. 1. 1.]]

-   Data types- NumPy allows for flexibility in interacting with data
    and their types.

-   You can convert an array from one data type to another using the
    astype method

    ``` python
    arr2 = np.array([1, 2, 3, 4, 5])

    print(arr2.dtype)

    float_arr = arr2.astype(np.float64)

    print(float_arr)

    print(float_arr.dtype)
    ```

        int64
        [1. 2. 3. 4. 5.]
        float64

-   You can also convert an array of strings that represent numbers to
    numeric form by using astype

    ``` python
    numeric_string = np.array(["1.8", "-10", "54.7"], dtype=np.string_)

    print(numeric_string)

    numeric_string.astype(float)

    print(numeric_string)
    ```

        [b'1.8' b'-10' b'54.7']
        [b'1.8' b'-10' b'54.7']

-   Numpy has various universal functions that perform useful element
    wise operations. Below are a few examples. Extensive documentation
    of NumPy’s universal functions can be found at

    <https://numpy.org/doc/stable/reference/routines.math.html>

In [6]:
#log10 example 
print(np.log10([1e-15, 456]))

#calculate log(exp(x1) + exp(x2))
#this is useful in statistics where calculated probablities may be too small 

prob1 = np.log(1e-50)
prob2 = np.log(2.5e-50)
prob12 = np.logaddexp(prob1, prob2)
print(prob12)


#sqrt example
print(np.sqrt([1,4,9]))

[-15.           2.65896484]
-113.87649168120691
[1. 2. 3.]